import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from prompts import GetPrompts
from get_instance import GetData
import types
import warnings
import sys
from collections import defaultdict
import numpy as np

class FJSP():
    def __init__(self):
        self.prompts = GetPrompts()

    def select_operation(self, num_jobs, num_job_operations, job_current_operation, machine_process_times, machine_available_time):
        job_scores = []
        all_machines = set()

        for j in range(num_jobs):
            if job_current_operation[j] >= num_job_operations[j]:
                job_scores.append(None)
                continue

            current_op = job_current_operation[j]
            eligible_machines = machine_process_times[j][current_op]

            if not eligible_machines:
                job_scores.append(None)
                continue

            # Calculate sum of minimal processing times for remaining ops (workload urgency)
            rem_min_proc = 0
            for op_i in range(current_op, num_job_operations[j]):
                ops_machines = machine_process_times[j][op_i]
                if not ops_machines:
                    continue
                rem_min_proc += min(pt for _, pt in ops_machines)

            # Earliest machine availability for current op
            earliest_avail = min(machine_available_time[m] for m, _ in eligible_machines)

            # Dynamically weighted harmonic mean to balance urgency and readiness
            alpha = 0.6 * (1 - current_op / (num_job_operations[j] + 1e-6)) + \
                    0.4 * (rem_min_proc / (rem_min_proc + earliest_avail + 1e-6))

            # Harmonic mean component (avoid zero division)
            score = (2 * alpha * rem_min_proc * (1 / (earliest_avail + 1e-6))) / \
                    (alpha * rem_min_proc + (1 - alpha) * (1 / (earliest_avail + 1e-6)) + 1e-6)

            job_scores.append(score)

            for m, _ in eligible_machines:
                all_machines.add(m)

        if all(s is None for s in job_scores):
            job_idx = None
        else:
            valid_scores = [(idx, s) for idx, s in enumerate(job_scores) if s is not None]
            job_idx = max(valid_scores, key=lambda x: x[1])[0]

        return job_idx
    
    def fjsp_solver(self, num_jobs, num_job_operations, machine_process_times, alg):
        '''
        input:
            num_jobs: the number of jobs
            num_job_operations: the number of operations of the each job, the value is the number of operations of the job
            num_machines: the number of machines
            machine_process_times: list of machine_process_time, the structure is as follows:
                machine_process_times[job_id][operation_id] = [(machine_id, process_time)]
            alg: the algorithm generated by the LLM
        output:
            min_makespan: the minimum makespan of the jobs
        '''
        schedule = []
        job_current_operation = [0] * num_jobs
        machine_available_time = defaultdict(int)
        job_available_time = [0] * num_jobs  # 每个作业的可用时间（上一道工序的完成时间）
        

        

        while True:
            job_idx = self.select_operation(num_jobs, 
                                           num_job_operations, 
                                           job_current_operation, 
                                           machine_process_times, 
                                           machine_available_time, 
                                           )
            if job_idx is None:
                break
            op_idx = job_current_operation[job_idx]
            # 1. 选择机器（返回真实的 machine_id）
            machine_id = alg.select_machine(machine_process_times[job_idx][op_idx], 
                                            machine_available_time)
            # 2. 计算加工时间：根据真实 machine_id 在 machine_process_times 中查找
            processing_time = None
            for mid, p_time in machine_process_times[job_idx][op_idx]:
                if mid == machine_id:
                    processing_time = int(p_time)  # 确保是Python原生类型
                    break
            if processing_time is None:
                raise ValueError(f"未在 machine_process_times 中找到 machine_id={machine_id} 对应的加工时间")
            # 3. 计算开始时间：同时满足机器可用时间和作业上一道工序完成时间
            # 开始时间 = max(机器可用时间, 作业上一道工序完成时间)
            start_time = int(max(int(machine_available_time[machine_id]), int(job_available_time[job_idx])))  # 确保是Python原生类型
            # 4. 计算结束时间
            end_time = int(start_time + processing_time)  # 确保是Python原生类型
            # 5. 更新调度记录和状态
            # 确保所有值都是Python原生类型，而不是numpy类型
            schedule.append((int(job_idx), int(op_idx), int(machine_id), int(start_time), int(end_time)))
            machine_available_time[machine_id] = int(end_time)  # 更新机器可用时间
            job_available_time[job_idx] = int(end_time)  # 更新作业可用时间（确保下一道工序必须在此之后开始）
            job_current_operation[job_idx] += 1
            makespan = int(max([int(entry[4]) for entry in schedule])) if schedule else 0  # 确保是Python原生类型
        # ===== 检查 schedule 是否正确 =====
        # 检查 schedule 是否正确：所有任务是否均完成其所有工序
        expected_total_ops = sum(num_job_operations)
        if len(schedule) != expected_total_ops:
            makespan = None 
        # 按作业统计 schedule 中的工序
        job_op_count = defaultdict(list)  # job_idx -> [op_idx, ...]
        for job_idx, op_idx, _, _, _ in schedule:
            job_op_count[job_idx].append(op_idx)
        for job_idx in range(num_jobs):
            expected_ops = num_job_operations[job_idx]
            actual_ops = sorted(job_op_count[job_idx])
            expected_op_indices = list(range(expected_ops))
            if len(actual_ops) != expected_ops:
                makespan = None
            if actual_ops != expected_op_indices:
                makespan = None
        return makespan, schedule

    # 评估函数，输入为字符串形式的代码，输出为适应度值
    # 在 Data/Dauzere 下所有 .fjs 实例上评测，每个实例得分为 (makespan-最优解)/最优解，最优解来自 Data/Dauzere.csv；去掉最大和最小后取平均作为 fitness
    def evaluate(self, code_string):
        try:
            # Suppress warnings
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")

                # Create a new module object
                heuristic_module = types.ModuleType("heuristic_module")
                
                # Execute the code string in the new module's namespace
                try:
                    exec(code_string, heuristic_module.__dict__)
                except SyntaxError as syn_err:
                    return None

                # Add the module to sys.modules so it can be imported
                sys.modules[heuristic_module.__name__] = heuristic_module

                # 相对 Data 的实例文件夹（与 get_instance.py、experiment.py 一致）
                _base_dir = os.path.dirname(os.path.abspath(__file__))
                rel_folder = "Dauzere"
                folder_path = os.path.join(_base_dir, "Data", rel_folder)
                if not os.path.isdir(folder_path):
                    return None

                # 加载 Dauzere.csv：第一列为实例文件名（无后缀），第二列为最优解
                optimal_csv_path = os.path.join(_base_dir, "Data", "Dauzere.csv")
                optimal_dict = {}
                if os.path.isfile(optimal_csv_path):
                    with open(optimal_csv_path, "r", encoding="utf-8") as f:
                        for line in f:
                            line = line.strip()
                            if not line:
                                continue
                            parts = line.split(",")
                            if len(parts) >= 2:
                                name_no_ext = parts[0].strip()
                                try:
                                    optimal_dict[name_no_ext] = float(parts[1].strip())
                                except ValueError:
                                    pass

                # 收集该文件夹下所有 .fjs 文件的 (makespan-最优解)/最优解；GetData 需传入相对 Data 的路径
                scores = []
                for fname in sorted(os.listdir(folder_path)):
                    if not fname.endswith(".fjs"):
                        continue
                    name_no_ext = os.path.splitext(fname)[0]
                    if name_no_ext not in optimal_dict:
                        continue
                    optimal = optimal_dict[name_no_ext]
                    if optimal <= 0:
                        continue
                    rel_to_data = os.path.join(rel_folder, fname).replace("\\", "/")
                    getdata = GetData(rel_to_data)
                    instance = getdata.get_instance()
                    if not instance or instance.get("num_jobs") is None:
                        continue
                    num_jobs = instance["num_jobs"]
                    num_job_operations = instance["num_job_operations"]
                    machine_process_times = instance["machine_process_times"]
                    makespan, _ = self.fjsp_solver(num_jobs, num_job_operations, machine_process_times, heuristic_module)
                    if makespan is not None:
                        relative_gap = (float(int(makespan)) - optimal) / optimal
                        scores.append(relative_gap)

                if not scores:
                    return None
                # 去掉最大和最小后取平均；不足 3 个则直接取平均
                if len(scores) >= 3:
                    scores_sorted = sorted(scores)
                    trimmed = scores_sorted[1:-1]
                else:
                    trimmed = scores
                fitness = float(sum(trimmed) / len(trimmed))
                return fitness
        except Exception as e:
            return None
        
if __name__ == "__main__":
    import json
    import os
    import time
    import types
    import sys
    
    # ============ 指定要测试的 generation 文件编号 ============
    GENERATION_NUM = 10  # 修改这个数字来指定要测试的文件，例如：10 表示 population_generation_10.json
    USE_POPS_DIR = False  # True: 使用 results/pops/ 目录（数组格式），False: 使用 results/pops_best/ 目录（单个对象）
    # ==========================================================
    
    fjsp = FJSP()
    from get_instance import GetData

    # 与 evaluate 一致：使用 Data/Dauzere 下所有 .fjs 实例；GetData 需传入相对 Data 的路径
    _base_dir = os.path.dirname(os.path.abspath(__file__))
    rel_folder = "Dauzere"
    folder_path = os.path.join(_base_dir, "Data", rel_folder)
    if not os.path.isdir(folder_path):
        print(f"错误: 数据文件夹不存在 - {folder_path}")
        sys.exit(1)
    instance_files = sorted([f for f in os.listdir(folder_path) if f.endswith(".fjs")])
    if not instance_files:
        print(f"错误: 未找到 .fjs 文件 - {folder_path}")
        sys.exit(1)
    print(f"评测实例列表 ({len(instance_files)} 个): {instance_files}")
    
    # 获取项目根目录（从 examples/user_fjsp/prob.py 向上三级）
    current_file = os.path.abspath(__file__)
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(current_file)))
    
    # 根据 USE_POPS_DIR 选择目录
    if USE_POPS_DIR:
        results_dir = os.path.join(project_root, 'eoh', 'results', 'pops')
    else:
        results_dir = os.path.join(project_root, 'eoh', 'results', 'pops_best')
    
    # 读取指定的 generation 文件
    json_file = os.path.join(results_dir, f'population_generation_{GENERATION_NUM}.json')
    
    if not os.path.exists(json_file):
        print(f"错误: 文件不存在 - {json_file}")
        sys.exit(1)
    
    # 存储所有测试结果
    all_results = []
    
    try:
        with open(json_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # 判断是数组格式还是单个对象格式
        if isinstance(data, list):
            algorithms = data
            print(f"\n{'='*80}")
            print(f"测试 Generation {GENERATION_NUM} (找到 {len(algorithms)} 个算法)")
            print(f"文件路径: {json_file}")
            print(f"{'='*80}\n")
        else:
            algorithms = [data]
            print(f"\n{'='*80}")
            print(f"测试 Generation {GENERATION_NUM} (找到 1 个算法)")
            print(f"文件路径: {json_file}")
            print(f"{'='*80}\n")
        
        
        # 遍历每个算法，在 Data/Dauzere 下所有实例上评测，去掉最大最小后取平均作为 fitness
        for idx, algo_data in enumerate(algorithms, start=1):
            code_string = algo_data.get('code', '')
            if not code_string:
                print(f"算法 {idx}: 跳过（没有找到 'code' 字段）")
                continue
            
            heuristic_module = types.ModuleType(f"heuristic_module_gen_{GENERATION_NUM}_algo_{idx}")
            try:
                exec(code_string, heuristic_module.__dict__)
            except Exception as e:
                print(f"\n{'='*80}")
                print(f"算法 {idx}: 代码执行失败")
                print(f"错误: {e}")
                import traceback
                traceback.print_exc()
                print(f"{'='*80}\n")
                continue
            
            sys.modules[heuristic_module.__name__] = heuristic_module
            
            print(f"\n{'='*80}")
            print(f"算法 {idx}/{len(algorithms)}")
            print(f"{'='*80}")
            
            start_time = time.time()
            makespans = []
            schedule = None  # 取第一个成功实例的 schedule 用于后续甘特图
            for fname in instance_files:
                rel_to_data = os.path.join(rel_folder, fname).replace("\\", "/")
                getdata = GetData(rel_to_data)
                instance = getdata.get_instance()
                if not instance or instance.get("num_jobs") is None:
                    continue
                num_jobs = instance["num_jobs"]
                num_job_operations = instance["num_job_operations"]
                machine_process_times = instance["machine_process_times"]
                try:
                    ms, sch = fjsp.fjsp_solver(num_jobs, num_job_operations, machine_process_times, heuristic_module)
                    if ms is not None:
                        makespans.append(float(int(ms)))
                        if schedule is None:
                            schedule = sch
                except Exception:
                    pass
            
            end_time = time.time()
            elapsed_time = end_time - start_time
            
            if not makespans:
                print(f"算法 {idx}: 所有实例均求解失败，跳过")
                continue
            
            # 与 evaluate 一致：去掉最大和最小后取平均
            if len(makespans) >= 3:
                trimmed = sorted(makespans)[1:-1]
            else:
                trimmed = makespans
            fitness = sum(trimmed) / len(trimmed)
            
            objective = algo_data.get('objective', 'N/A')
            algorithm_desc = algo_data.get('algorithm', 'N/A')
            algorithm_desc_short = algorithm_desc[:200] + "..." if len(algorithm_desc) > 200 else algorithm_desc
            
            result = {
                'index': idx,
                'makespans': makespans,
                'fitness': fitness,
                'elapsed_time': elapsed_time,
                'objective': objective,
                'algorithm': algorithm_desc,
                'schedule': schedule
            }
            all_results.append(result)
            
            print(f"测试结果:")
            print(f"  各实例 makespan: {makespans}")
            print(f"  fitness (去极值平均): {fitness:.2f}")
            print(f"  总运行时间: {elapsed_time:.4f} 秒")
            print(f"  objective (from JSON): {objective}")
            print(f"  算法描述: {algorithm_desc_short}")
            print(f"{'='*80}")
        
        # 打印汇总结果（按 fitness 排序）
        if all_results:
            print(f"\n{'='*80}")
            print("汇总结果 (fitness = 各实例 makespan 去最大最小后取平均):")
            print(f"{'算法编号':<10} {'Fitness':<12} {'运行时间(s)':<15} {'Objective':<12}")
            print(f"{'-'*80}")
            for r in sorted(all_results, key=lambda x: x['fitness']):
                print(f"{r['index']:<10} {r['fitness']:<12.2f} {r['elapsed_time']:<15.4f} {r['objective']:<12}")
            print(f"{'='*80}")
            
            best = min(all_results, key=lambda x: x['fitness'])
            print(f"\n最佳结果: 算法 {best['index']}, Fitness = {best['fitness']:.2f}")
            print(f"{'='*80}\n")
        else:
            print("\n未成功测试任何算法\n")
            
    except Exception as e:
        print(f"错误: 文件读取失败 - {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    
    # 甘特图与调度详情：取第 print_index 个算法的 schedule（0 表示第一个，1 表示第二个）
    print_index = min(1, len(all_results) - 1) if all_results else 0
    if not all_results or all_results[print_index].get('schedule') is None:
        print("无有效 schedule，跳过调度详情与甘特图")
        sys.exit(0)
    schedule = all_results[print_index]['schedule']
    #  ============  打印调度详情  =============
    print("Schedule (每行一个工序):")
    for entry in schedule:
        # entry: (job_id, op_id, machine_id, start_time, end_time)
        print(f"作业{entry[0]}, 工序{entry[1]}, 机器{entry[2]}, 开始{entry[3]}, 结束{entry[4]}")

    #  ============  甘特图  =============
    import matplotlib.pyplot as plt
    job_ids = sorted(set([e[0] for e in schedule]))
    color_map = {}
    cmap = plt.colormaps.get_cmap('tab10')
    for idx, job_id in enumerate(job_ids):
        color_map[job_id] = cmap(idx % 10)
    fig, ax = plt.subplots(figsize=(10, 6))
    for job_id, op_id, machine_id, start_time, end_time in schedule:
        ax.barh(
            y=machine_id,
            width=end_time - start_time,
            left=start_time,
            height=0.6,
            color=color_map[job_id],
            edgecolor='black',
        )
        ax.text(
            start_time + (end_time - start_time) / 2,
            machine_id,
            f'J{job_id}-O{op_id}',
            va='center',
            ha='center',
            color='white',
            fontsize=8,
            fontweight='bold',
        )

    ax.set_ylabel("机器ID")
    ax.set_xlabel("时间")
    ax.set_title("FJSP 甘特图 (不同颜色区分不同工件)")

    # 构建图例（每个 job 一个颜色）
    handles = [plt.Rectangle((0, 0), 1, 1, color=color_map[jid]) for jid in job_ids]
    labels = [f"作业{jid}" for jid in job_ids]
    ax.legend(handles, labels, title='工件')

    ax.set_yticks(sorted(set([e[2] for e in schedule])))
    plt.tight_layout()
    plt.show()
